version: "3.7"

services:

  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 3s
      timeout: 2s
      retries: 10

  server:
    build: .
    platform: linux/amd64
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: sh entrypoint.sh


volumes:
  postgres-data:
